PRAGMA auto_vacuum = 1;
PRAGMA encoding = "UTF-8";

DROP TABLE IF EXISTS "BAR";

CREATE TABLE "BAR"
(
    "ID"  INTEGER      CONSTRAINT "SECTION_PK" PRIMARY KEY,
    "BAR" VARCHAR(255) NOT NULL
);
